############################################################################
# Implements Lemma 4.1 of Laumen & Cramer (2019), "Stage life testing",
# Naval Research Logistics 66:632-647 -- the paper this package's two-stage
# cumulative-exposure model is based on -- for the *random-withdrawal* SLT
# design (Procedure 2.3), as generated by rslt().
#
# At the stage-change time tau1, R*_1 of the (n - D1) units still surviving
# are moved to stage 1; D1 (the number of stage-0 failures observed before
# tau1) is Binomial(n, F0(tau1)) for *any* continuous stage-0 distribution
# F0. Two selection rules are supported (the paper's "Type-P" and
# "Type-M"):
#   Type-P: R*_1 = floor(pi1 * (n - D1))        (a fixed target PROPORTION)
#   Type-M: R*_1 = min(n - D1, R0_1)             (a fixed target COUNT)
############################################################################

#' Probability of observing at least one stage-1 failure (Laumen & Cramer, Lemma 4.1)
#'
#' Computes the probability of observing at least one stage-1 failure,
#' `P(R*_1 > 0)`, implementing Lemma 4.1 of Laumen & Cramer (2019).
#'
#' @details
#' Because the maximum likelihood estimate of the elevated-stage parameter
#' only exists when at least one unit is actually transferred to stage 1
#' and fails there (`R*_1 > 0`), this is a useful quantity for planning a
#' stage life test: choosing `n`, `tau1`, and `pi1`/`R0_1` so that
#' `slt_prob_stage1()` is comfortably close to 1.
#'
#' `R*_1 = rho(D1) > 0` iff `D1 <= n*`, where `n* = floor(n - 1/pi1)` for
#' the `"typeP"` design and `n* = n - 1` for the `"typeM"` design (with
#' `R0_1 >= 1`), and `D1 ~ Binomial(n, F0(tau1))`.
#'
#' @inheritParams slt_equiv_age
#' @param n Number of units placed on test.
#' @param tau1 Stage-change time.
#' @param design `"typeP"` (fixed target proportion `pi1`) or `"typeM"`
#'   (fixed target count `R0_1`), matching [rslt()].
#' @param pi1 Target proportion transferred, for `design = "typeP"`.
#' @param R0_1 Target number transferred, for `design = "typeM"`.
#' @return A list with `n_star` (the threshold on `D1`) and `prob`
#'   (`P(R*_1 > 0)`).
#' @export
#' @examples
#' # Reproduces Table 5 of Laumen & Cramer (2019) exactly (n = 12,
#' # theta0 = 1 i.e. lambda0 = 1, tau1 = 0.5):
#' slt_prob_stage1(12, 0.5, c(1, 1), design = "typeP", pi1 = 0.25)  # n*=8,  prob=0.9864756680
#' slt_prob_stage1(12, 0.5, c(1, 1), design = "typeM", R0_1 = 6)    # n*=11, prob=0.9999862301
slt_prob_stage1 <- function(n, tau1, theta0, family = "weibull",
                             design = c("typeP", "typeM"),
                             pi1 = NULL, R0_1 = NULL) {
  design <- match.arg(design)
  fam <- get_family(family)
  F0_tau1 <- fam$cdf(tau1, theta0)
  n_star <- if (design == "typeP") {
    if (is.null(pi1) || pi1 <= 0 || pi1 > 1) {
      stop("'pi1' must be in (0, 1] for design = 'typeP'.", call. = FALSE)
    }
    floor(n - 1 / pi1)
  } else {
    if (is.null(R0_1) || R0_1 < 0 || R0_1 != round(R0_1)) {
      stop("'R0_1' must be a non-negative integer for design = 'typeM'.", call. = FALSE)
    }
    if (R0_1 >= 1) n - 1L else -1L
  }
  prob <- if (n_star < 0) 0 else stats::pbinom(min(n_star, n), size = n, prob = F0_tau1)
  list(n = n, tau1 = tau1, F0_tau1 = F0_tau1, design = design,
       pi1 = pi1, R0_1 = R0_1, n_star = n_star, prob = prob)
}
